spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Aa123456#
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-provider
dubbo:
  registry:
    address: localhost:8848
    protocol: nacos
    register-mode: instance
  protocol:
    port: -1
  provider:
    loadbalance: shortestresponse
mybatis-flex:
  audit-enable: true
  global-config:
    print-banner: false