server:
  port: 80
springdoc:
  title: spring-ex测试接口文档
  version: 1.0.4-jdk17on
  group-configs:
    - group: test
      display-name: 测试
      packages-to-scan:
        - com.guanmengyuan.spring.ex.test
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Aa123456#
mybatis-flex:
  audit-enable: true
  global-config:
    print-banner: false
