server:
  port: ${SERVER_PORT:80}
spring:
  application:
    name: gateway
  cloud:
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: ${SENTINEL_HOST:localhost}:${SENTINEL_POST:8081}
        client-ip: ${SENTINEL_HOST:localhost}
        port: 8719
    gateway:
      routes:
        - id: user-consumer
          uri: lb://user-consumer
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
    nacos:
      server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
      excluded-services:
        - gateway
management:
  endpoints:
    web:
      exposure:
        include: "*"