spring:
  application:
    name: user-consumer
  webflux:
    ignores:
      - /re/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
dubbo:
  registry:
    address: ${spring.cloud.nacos.server-addr}
    protocol: nacos
    register-mode: instance
  protocol:
    port: -1
  application:
    register-consumer: false
  consumer:
    retries: 0
    timeout: 60000
    loadbalance: shortestresponse
    check: false

server:
  port: 81
springdoc:
  title: 测试接口文档
  group-configs:
    - group: default
      packages-to-scan:
        - com.guanmengyuan.spring.cloud.example.consumer.controller
      display-name: 测试
